# Sidebar navigation

- label: 'Recent Posts'
  link: '/'

- label: 'Who am I ?'
  link: '/me'

- label: 'Find me'
  link: '/contact'

- label: Recent Projects
  items:
    - label: 'Developers Community'
      link: '/projects/CDC'
    - label: 'DashB - No code ML'
      link: '/projects/dashb'
    - label: 'DashViz - A Visualization Tool'
      link: '/projects/dashviz'
    - label: 'More ...'
      link: '/projects/all-projects'

- label: Roadmap
  items:
    - label: 'Roadmap'
      link: '/roadmap/roadmap'

- label: My Notes | Blog
  items:
    - label: 'Data Science'
      link: '/notes/DS/all-collection'

    - label: 'Statistics'
      link: 'notes/stats/all-stats'

    - label: 'Machine Learning'
      link: '/notes/ML/all-ml'

    - label: 'Deep Learning'
      link: '/notes/DL/all-dl'

    - label: 'Deployment'
      link: '/notes/deploy/all-deploy'
    
    - label: 'Streamlit'
      link: '/notes/framework/streamlit-starter-notes'
      
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/IMSumitKumar
