# Sidebar navigation

- label: 'Who am I ?'
  link: '/'

- label: 'Find me'
  link: '/contact'

- label: Recent Projects
  items:
    - label: 'Developers Community'
      link: '/projects/CDC'
    - label: 'DashB - No code ML'
      link: '/projects/dashb'
    - label: 'DashViz - A Visualization Tool'
      link: '/projects/dashviz'
    - label: 'More ...'
      link: '/projects/all-projects'

- label: My Notes | Blog
  items:
    - label: 'Data Visualization'
      link: '/usage/shadowing'
    - label: 'Web Scrapping'
      link: '/usage/creating-docs'
    - label: 'Machine Learning'
      link: '/usage/navigation'
    - label: 'Deep Learning'
      link: '/usage/shadowing'
      
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/IMSumitKumar
